// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD88OUkbibc7rc0dI-zDJOEm0el-tRjIZs',
    appId: '1:14643166336:web:879dd9908af858b1797a65',
    messagingSenderId: '14643166336',
    projectId: 'mybreathwork-a7a56',
    authDomain: 'mybreathwork-a7a56.firebaseapp.com',
    storageBucket: 'mybreathwork-a7a56.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXsigPeV78Pd_YzLBFgW_q2eBo9W_kLGI',
    appId: '1:14643166336:android:9576477088bebf85797a65',
    messagingSenderId: '14643166336',
    projectId: 'mybreathwork-a7a56',
    storageBucket: 'mybreathwork-a7a56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi9oJNr4Ra9NHBzpJvNdF3rJRuTJ_3oLg',
    appId: '1:14643166336:ios:bcc7585f2b4ab0be797a65',
    messagingSenderId: '14643166336',
    projectId: 'mybreathwork-a7a56',
    storageBucket: 'mybreathwork-a7a56.firebasestorage.app',
    iosBundleId: 'com.example.myBreathWork',
  );
}
