// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7LJ4eonkIP64qX6oTCAJ7UpGUd7uoQnQ',
    appId: '1:305474624030:web:1b3f954b8566307b47ec0f',
    messagingSenderId: '305474624030',
    projectId: 'mybreathwork-77f50',
    authDomain: 'mybreathwork-77f50.firebaseapp.com',
    storageBucket: 'mybreathwork-77f50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf-y4-XGlvJhTOlISw1mZxSeECX3szSJg',
    appId: '1:305474624030:android:6ffe5e853c72e70947ec0f',
    messagingSenderId: '305474624030',
    projectId: 'mybreathwork-77f50',
    storageBucket: 'mybreathwork-77f50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCfF_Wgj8zYH_bZPSMd3YyFHQFN4fEo2M',
    appId: '1:305474624030:ios:532f2bee1ebfb59f47ec0f',
    messagingSenderId: '305474624030',
    projectId: 'mybreathwork-77f50',
    storageBucket: 'mybreathwork-77f50.appspot.com',
    iosBundleId: 'com.example.myBreathWork',
  );
}
